#!/bin/bash

fail='[\033[1;31mfail\033[0m]'
ok='[\033[1;32mOK\033[0m]'

#设定默认指令
if [ -z "$1" ];then
	cmd='start'
else
	cmd=$1
fi

case $cmd in
	start)
		start
		exit 0;;
   
	stop)
		stop
		exit 0;;
    status)
		status
		exit 0;;
	list)
		list
		exit 0;;
	restart)
		restart
		exit 0;;
	*)
		echo "usage $0 [start|stop|status|list|restart] "
		exit 1;;
esac
exit 0