#!/bin/bash

fail='[\033[1;31mfail\033[0m]'
ok='[\033[1;32mOK\033[0m]'

#设定默认指令为start  
if [ -z "$1" ];then
	cmd='start'
else
	cmd=$1
fi
#移除动作参数 
shift


echo $1 
exit;
#启动应用
start(){
	echo $@
	echo $1
	shift
	echo $1 
}

#停止应用
stop(){
	echo 'stop'
}

#获取应用状态
status(){
	echo 'status'
}
#应用列表
list(){
	echo 'list'
}

#重启应用
restart(){
	stop
	start
	echo -e "restart $ok"
}

case $cmd in
	start)
		start $@
		exit 0;;
	stop)
		stop
		exit 0;;
    status)
		status
		exit 0;;
	list)
		list
		exit 0;;
	restart)
		restart
		exit 0;;
	*)
		echo "usage $0 [start|stop|status|list|restart] "
		exit 1;;
esac
exit 0
